### ISSUE TITLE
Feedback for “Import Export”

### ISSUE THREAD

**Issue by rainxw** [dream-num/univer.ai#223]
Regarding the file import and export scenarios:
It is necessary to deploy a backend service to achieve this, which is highly restrictive for project development. It is not feasible to deploy an additional service just to implement Excel import and export functionality.
Can you provide a frontend API method that can read Excel files and obtain the corresponding Univer sheet data?

针对文件导入导出的场景：
1.必须要部署后端服务才能实现，这个针对项目开发中局限性太高了，不可能额外去部署一个服务来实现excel的导入导出
2.能否提供前端api接口方法，可以读取excel文件，来获取对应的univer sheet数据？

**Comment by jikkai** [comment]
1. Importing & exporting are inherently high-performance tasks. According to our tests, a purely front-end implementation (including wasm) cannot achieve enterprise-level usability. Therefore, for users with this requirement, we suggest considering implementing it on the server side. **In short, due to considerations such as performance, the official temporarily does not consider providing a pure front-end solution.**
2. We do not limit users to using our server-side import and export services; users can fully implement front-end parsing of xlsx and execute various commands provided by Univer to realize import and export functions based on various open-source solutions. In fact, there are already quite a few cases in the community that have implemented similar capabilities.

---

1. 导入导出本来就是具有较高性能开销的工作，根据我们的测试，纯前端的实现（包括 wasm）并不能达到企业级可用的效果，因此对于有该需求的用户，我们建议考虑在服务端实现。简而言之，基于性能等因素的考虑，官方暂时不考虑直接提供纯前端方案。
2. 我们并没有限制用户必须使用我们的服务端导入导出，用户完全可以基于各种开源方案来实现前端解析 xlsx 并执行 Univer 所提供的各种命令来实现导入和导出功能。事实上社区中已经有不少实现类似能力的案例了。
