### ISSUE TITLE
为什么使用自定义ui功能时，复制代码会提示缺少OnLifecycle？

### ISSUE THREAD

**Issue by wangrunfa0917** [dream-num/univer.ai#340]
![image](https://github.com/user-attachments/assets/c9b8ccbf-986d-4cbf-ac3d-b0afd9613047)

**Comment by wzhudev** [comment]
Hi @wangrunfa0917 . Thanks for your question. That is a good one. In fact we have removed this API `OnLifecycle` on an earlier version because it does not work as we expected. Now you can use `touchDependencies` instead which you can find in our codebase. We have started updating related documents but they have not been published yet. Sorry for the inconvenience.
